/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.observerpattern;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Elton
 */
public class SimpleTheaterObserver extends javax.swing.JFrame implements IObserver{
    
    MovieRaterSubject subject;
    String observerName = "Simple Screen Observer";
    
    /**
     * Creates new form UserScreenObserver
     */
    public SimpleTheaterObserver(MovieRaterSubject subject, int nameSuffix) {
        this.observerName = observerName + " " + nameSuffix;
        this.subject = subject;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Register = new javax.swing.JButton();
        btn_Deregister = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setTitle(observerName);

        btn_Register.setText("Register");
        btn_Register.setName("btn_Register"); // NOI18N
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register(evt);
            }
        });

        btn_Deregister.setText("De-Register");
        btn_Deregister.setActionCommand("deRegister");
        btn_Deregister.setName("btn_Deregister"); // NOI18N
        btn_Deregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deRegister(evt);
            }
        });

        jScrollPane2.setName("lb_MovieList"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Deregister, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btn_Deregister, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deRegister(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deRegister
        subject.unRegister(this);
    }//GEN-LAST:event_deRegister

    private void register(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register
            subject.register(this);
    }//GEN-LAST:event_register



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Deregister;
    private javax.swing.JButton btn_Register;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(List<Movie> movies) {
        DefaultListModel<String> model = new DefaultListModel<>();
        
       for(Movie m:movies){
           model.addElement(m.getName()+ " " + m.getRating());
       }
       jList1.setModel(model);
       jList1.setSelectedIndex(0);
    }

 
    @Override
    public void updateLuxuryObserver() {
        //DO NOTHING!
    }
}
